### ISSUE TITLE
wiki minor edit

### ISSUE THREAD

**Issue by besmirzanaj** [regnauld/stuff#1]
HI,
please edit the GestioIP link in the wiki site:
https://github.com/regnauld/stuff/wiki/IPAM-tools

to: https://www.gestioip.net/

**Comment by regnauld** [comment]
Thanks! That was definitely a copy-paste error :)

Also, I have an updated version at https://gist.github.com/regnauld/63866f968d6cf55f29845a6d896b5b65

**Comment by besmirzanaj** [comment]
That was fast
